version: "3.8"
services:
  basketball-app:
    container_name: basketball_app
    image: akshay2323/basketball_app:latest
    build: .
    ports:
    - published: 80
      target: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@basketball_database:3306/basketball
      CREATE_SCHEMA:
    depends_on:
    - database  
  database:
    container_name: basketball_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: basketball