version: "3.8"
services:
  fantasy-basketball-app:
    container_name: 
    image: 
    build: .
    ports:
    - published: 80
      target: 5000
    environment:
      DATABASE_URI: 
      CREATE_SCHEMA:
    depends_on:
    - database  
  database:
    container_name: 
    image: 
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: 
    volumes:
    - type: 
      source: 
      target: 
volumes:
  fantasybasketball_database_volume: