version: "3.8"
services:
  fantasybasketball-app:
    container_name: fantasybasketball_app
    image: akshay2323/basketball_app:latest
    build: .
    ports:
    - published: 80
      target: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@fantasybasketball_database:3306/fantasybasketball
      CREATE_SCHEMA:
    depends_on:
    - database  
  database:
    container_name: fantasybasketball_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: fantasybasketball
    restart: always  
    ports:
    - "3306:3306"


